<?php require_once '_header.php'; ?>

<main>
	<div class="inner">
		<article class="pageArticle formattedContent">
			<p>My mother, Susan Lynn Correll Kobarg, was born crazy about horses. In fact, my grandparents swear her first word was "horse." My grandfather was a senior executive for Montgomery Wards; his uniform was a 3-piece suit. My grandparents didn't know the front end of a horse from the back end. When my mother was eight, my grandparents enrolled my mother in riding lessons at a local Saddlebred farm hoping to satisfy my mother's obsession. It didn't work. Mom spent every waking moment riding, grooming, breathing or dreaming horses. When Mom was twelve, my grandparents bought her first horse-a young Arabian colt. My grandparents, still having no clue about horses, kept the colt in their suburban backyard; that is, until he jumped the fence and ate the neighbors award winning roses.</p>
			<figure class="fullwidth transparent">
				<img src="images/article.jpg" alt="" />
			</figure>
			<p>As Mom grew up she learned a lot about horses, both the hard way and through the help of her other neighbor who was a veterinarian. Mom went to college at the University of Texas at Austin where she met my father, R. J. "Buddy" Kobarg. Upon graduation and at the height of the Vietnam War, Dad joined the Air Force. While Dad flew combat missions in Vietnam, Mom devoted her time to the horses. They purchased a young colt sired by Zarabo named Valentino Rojo++ (pictured below). Mom and Dad took "Rojo" to his Legion of Merit in Halter, English Pleasure, Western, and Native Costume-you name it, Rojo did it.</p>
			<p>This is where I (Kristin Kobarg Herder) come into the picture. I was born in Shreveport, Louisiana in 1974. In 1975 the Air Force moved our family to Sacramento, California where Mom's horse business took off and with it, many wonderful, funny and loving stories-more to come!! My sister Kelley was born in 1978 and Mom decided to hang up the show reins and be a "Mom"; she wanted to devote more time to taking care of Kelley and I-ballet, piano lessons and soccer practice. Then Dad received orders and we moved to Omaha Nebraska. Before the move, Mom sold all the horses except Rojo, Roiya and their foundation mare Saturn's Greylight (Hassan) which we brought with us. While in Nebraska, and shortly after the 1981 Pentathlon Mom sold Rojo to a wonderful family. Hassan was sent to stay with lifelong friends in Shreveport (Terry and Jackie Taraba) to be a broodmare. We only had Mom's favorite filly, Roiya.</p>
<!--			
			<h1>Sed tincidunt placerat</h1>
			<p>Lorem <a href="#">ipsum dolor sit</a> amet, consectetur adipiscing elit. Vestibulum vulputate, tortor in imperdiet sagittis, nisl nisl commodo nulla, vitae iaculis mi elit et justo. Phasellus vel fermentum nisl. Aenean porta arcu at ipsum vehicula vestibulum. Integer eu sem egestas quam vehicula cursus nec eget sapien. Mauris a dapibus enim. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In ornare non turpis et tempor. Curabitur id varius sapien. Donec a ante molestie, bibendum ante id, ornare mi. Proin eget mi enim. Duis tempus est at nisi sagittis, et suscipit arcu tincidunt. Etiam ullamcorper nisi elit, id laoreet leo suscipit eu. Sed ut posuere ligula, eu malesuada arcu. Suspendisse volutpat a massa id tincidunt. Maecenas efficitur tincidunt turpis et venenatis.</p>
			<p>Quisque in lacus urna. Sed tincidunt placerat metus sit amet bibendum. Vestibulum sed tellus lacus. Nunc consequat nisi id tempor gravida. Pellentesque aliquam pulvinar vehicula. Proin sollicitudin arcu libero, nec ultricies ex molestie a. In non imperdiet arcu. Pellentesque tempor, odio eget tempus tristique, libero est vestibulum mi, molestie ullamcorper turpis lectus tempus eros. Integer non arcu blandit, facilisis quam et, aliquam odio. Aenean feugiat facilisis dolor a posuere. Cras rhoncus quis ex eu ultricies.</p>
			<h2>Nullam nec enim</h2>
			<p>Mauris vehicula tellus vel orci maximus consectetur. Quisque non lectus massa. Nullam nec enim rhoncus, sagittis tortor eget, euismod nisl. Donec sed nisl erat. Etiam id mi eget risus interdum imperdiet accumsan id quam. Aenean tincidunt lorem dui, pulvinar dignissim lorem finibus sed. Quisque non massa in elit tincidunt semper ut et velit. Aenean pellentesque, ligula nec tristique sollicitudin, leo sapien bibendum odio, sed ornare metus turpis in metus. Nam nunc lorem, tristique id massa a, bibendum vulputate ante. Suspendisse id imperdiet elit. </p>
			<h3>Mom grew up</h3>
			<p>As Mom grew up she learned a lot about horses, both the hard way and through the help of her other neighbor who was a veterinarian. Mom went to college at the University of Texas at Austin where she met my father, R. J. "Buddy" Kobarg. Upon graduation and at the height of the Vietnam War, Dad joined the Air Force. While Dad flew combat missions in Vietnam, Mom devoted her time to the horses. They purchased a young colt sired by Zarabo named Valentino Rojo++ (pictured below). Mom and Dad took "Rojo" to his Legion of Merit in Halter, English Pleasure, Western, and Native Costume-you name it, Rojo did it.</p>
			<ul>
				<li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum vulputate, tortor in imperdiet sagittis, nisl nisl commodo nulla, vitae iaculis mi elit et justo.</li>
				<li>Quisque non lectus massa.</li>
				<li>Nullam nec enim rhoncus, sagittis tortor eget, euismod nisl. Donec sed nisl erat.</li>
			</ul>
			<p>This is where I (Kristin Kobarg Herder) come into the picture. I was born in Shreveport, Louisiana in 1974. In 1975 the Air Force moved our family to Sacramento, California where Mom's horse business took off and with it, many wonderful, funny and loving stories-more to come!! My sister Kelley was born in 1978 and Mom decided to hang up the show reins and be a "Mom"; she wanted to devote more time to taking care of Kelley and I-ballet, piano lessons and soccer practice. Then Dad received orders and we moved to Omaha Nebraska. Before the move, Mom sold all the horses except Rojo, Roiya and their foundation mare Saturn's Greylight (Hassan) which we brought with us. While in Nebraska, and shortly after the 1981 Pentathlon Mom sold Rojo to a wonderful family. Hassan was sent to stay with lifelong friends in Shreveport (Terry and Jackie Taraba) to be a broodmare. We only had Mom's favorite filly, Roiya.</p>
			-->
		</article>
	</div>
</main>

<?php require_once '_footer.php';